* HBase FileInputFormats for RHIPE
This is a JAR file which can be included in the command =rhmr= to
access HBase databases. 

The FileInputFormats are specific to Mozilla's Socorro Crash Report
Hbase file structure and Telemetry schema.

The class =RHHBaseGeneral= should work with String keys and general
values. The returned value is a list of lists. Each sublist
entry has two elements (as is usual in RHIPE) - the key and value.

The value (the second entry) has the names attribute equal to
=columnfamily:columnname= .  The values are raw bytes (and if the raw
bytes correspond to Java strings, they can be converted using the R
function =rawToChar=). The keys are also raw bytes.

( To build this, keep Rhipe.jar in the java/lib folder and create that
folder if necc.)

Some sample R code

#+BEGIN_SRC R
library(Rhipe)
rhinit()
options(width=200)
rhoptions(runner="sh ./Rfolder/Rdist/mscript.sh")

hbasemap <- function(tablename, colspec, rows,caching=3L, cacheBlocks=TRUE){
  ## This function can be used when ever accessing Hbase
  mapred <- list()
  mapred$rhipe.hbase.tablename <- as.character(tablename[1])
  mapred$rhipe.hbase.colspec <- paste(colspec,collapse=",")
  mapred$rhipe.hbase.rowlim.start <-rows[1] 
  mapred$rhipe.hbase.rowlim.end <- rows[2]
  mapred$rhipe.hbase.mozilla.cacheblocks <- sprintf("%s:%s",as.integer(caching),as.integer(cacheBlocks))
  mapred$rhipe.hbase.mozilla.prefix <- "byteprefix"
  mapred$rhipe_inputformat_class <- 'org.godhuli.rhipe.hbase.RHCrashReportTableInputFormat'
  mapred$rhipe_inputformat_keyclass <- 'org.godhuli.rhipe.hbase.RHBytesWritable'
  mapred$rhipe_inputformat_valueclass <- 'org.godhuli.rhipe.hbase.RHResult'
  mapred
}

rhput("~/rhipecrashreport.jar","/user/sguha/tmp/")

mapred <- hbasemap("telemetry",colspec="data:json",rows=c("20120101","20120101"))
z <- rhmr(map=expression(
    lapply(map.values,function(r){
      rhcollect(NULL,r)
    })
    ),ofolder='/user/sguha/tmp/deletemeNOW'
          ,inout=c(NA,'seq')
          ,zips="/user/sguha/Rfolder.tar.gz"
          ,jarfiles="/user/sguha/tmp/rhipecrashreport.jar",
          ,jobname='Rhipe and Hbase and Telemetry'
          ,mapred=mapred)
rhstatus(rhex(z,async=TRUE), mon.sec=10)

y=rhread('/user/sguha/tmp/deletemeNOW/p*', max=10)
 w=lapply(y, function(r) lapply(r[[2]],rawToChar)) ## since in the map i output NULL, i dont care to rawToChar it
#+END_SRC

